### ISSUE TITLE
npm run storybook:build:all

### ISSUE THREAD

**Issue by kars-springbok** [Edd-Strickland/stencilbook#1]
If I run this command the watch and serve don't work. So if I update a web component it won't reflect in Storybook.

**Comment by Edd-Strickland** [comment]
Let me take a look

**Comment by kars-springbok** [comment]
Seems like stencil:start and storybook need to run side by side in order for it to work

**Comment by Edd-Strickland** [comment]
I've added the http-serve package to the dependancies.  This should resolve had this added locally so was running in the background

**Comment by Edd-Strickland** [comment]
but for live reload just run the commands as detailed in the readme `npm run build:all` and then `npm run storybook` and this will run the watch mode for both so when any changes are made to the stories or the stencil web component it'll update.
